USE hoeung_phase3;
DROP TABLE IF EXISTS UW_DEPENDENT;
DROP TABLE IF EXISTS UW_WORKS_ON;
DROP TABLE IF EXISTS UW_PROJECT;
DROP TABLE IF EXISTS UW_DEPT_LOCATIONS;
DROP TABLE IF EXISTS UW_MANAGER;
DROP TABLE IF EXISTS UW_EMPLOYEE;
DROP TABLE IF EXISTS UW_DEPARTMENT;
